'use client'

import { useEffect, useState, Suspense } from 'react'
import { useSavesStore } from '@/src/store/savesStore'
import { useRetinueStore } from '@/src/store/retinueStore'
import type { Retinue, Group } from '@/src/types'
import { computeGroupCost, computeRetinueCost } from '@/src/logic/costs'
import { unitTypeById } from '@/src/data/unitTypes'
import { weaponById, armourById, shieldById, mountById } from '@/src/data/equipment'
import { abilityById } from '@/src/data/abilities'
import { useSearchParams } from 'next/navigation'

function PrintContent() {
  const searchParams = useSearchParams()
  const id = searchParams.get('id') ?? 'current'
  const [retinue, setRetinue] = useState<Retinue | null>(null)
  const saves = useSavesStore(s => s.saves)
  const currentRetinue = useRetinueStore(s => s.retinue)

  useEffect(() => {
    const saved = saves.find(s => s.data.id === id)
    if (saved) {
      setRetinue(saved.data)
    } else if (currentRetinue.id === id || id === 'current') {
      setRetinue(currentRetinue)
    }
  }, [id, saves, currentRetinue])

  if (!retinue) {
    return (
      <div className="flex items-center justify-center h-screen">
        <p className="text-muted-foreground">Retinue not found.</p>
      </div>
    )
  }

  const totalCost = computeRetinueCost(retinue)

  return (
    <div className="bg-white text-black min-h-screen p-8 print:p-4 font-sans">
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Header */}
        <div className="border-b-2 border-black pb-4">
          <h1 className="text-2xl font-bold font-serif">{retinue.name}</h1>
          <p className="text-sm text-gray-600 mt-1">
            The Barons&apos; War · Feudal European · {totalCost} / {retinue.pointsLimit} pts
          </p>
        </div>

        {/* Groups */}
        <div className="space-y-4">
          {retinue.groups.map(group => (
            <PrintGroupRow key={group.id} group={group} />
          ))}
        </div>

        {/* Footer */}
        <div className="border-t border-gray-300 pt-3 text-xs text-gray-400 flex justify-between">
          <span>Generated by Barons&apos; War Retinue Builder</span>
          <span>Total: {totalCost} pts</span>
        </div>
      </div>

      <style>{`
        @media print {
          @page { size: A4; margin: 15mm; }
          body { print-color-adjust: exact; }
          .no-print { display: none; }
        }
      `}</style>

      <div className="no-print mt-8 text-center">
        <button
          onClick={() => window.print()}
          className="px-4 py-2 bg-black text-white rounded text-sm hover:bg-gray-800"
        >
          Print / Save as PDF
        </button>
      </div>
    </div>
  )
}

export default function PrintPage() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center h-screen"><p>Loading...</p></div>}>
      <PrintContent />
    </Suspense>
  )
}

function PrintGroupRow({ group }: { group: Group }) {
  const unitType = unitTypeById[group.unitTypeId]
  if (!unitType) return null
  const cost = computeGroupCost(group)
  const isCommander = unitType.isCommander
  const equipment = isCommander && group.commander ? group.commander.equipment : group.equipment

  const equipParts: string[] = []
  if (equipment.meleeWeapon) equipParts.push(weaponById[equipment.meleeWeapon]?.name ?? '')
  if (equipment.rangedWeapon) equipParts.push(weaponById[equipment.rangedWeapon]?.name ?? '')
  if (equipment.armour) equipParts.push(armourById[equipment.armour]?.name ?? '')
  if (equipment.shield) equipParts.push(shieldById[equipment.shield]?.name ?? '')
  if (equipment.mount) equipParts.push(mountById[equipment.mount]?.name ?? '')

  const cgUpgrades: string[] = []
  if (group.commandGroupUpgrade.banner) cgUpgrades.push('Bannerman')
  if (group.commandGroupUpgrade.pennant) cgUpgrades.push('Pennant')
  if (group.commandGroupUpgrade.musician) cgUpgrades.push('Musician')
  if (group.commandGroupUpgrade.priest) cgUpgrades.push('Priest')

  const abilities = [
    ...unitType.inherentAbilities,
    ...(isCommander ? (group.commander?.purchasedAbilities ?? []) : group.purchasedAbilities),
  ].map(id => abilityById[id]?.name ?? id.replace(/_/g, ' ')).join(', ')

  const stats = unitType.stats[group.experience]

  return (
    <div className="border border-gray-200 rounded p-3 text-sm">
      <div className="flex justify-between items-start">
        <div>
          <span className="font-bold">
            {isCommander && group.commander?.isRetinueLeader ? '★ ' : ''}
            {isCommander && group.commander?.name ? `${group.commander.name} · ` : ''}
            {unitType.name}
          </span>
          <span className="text-gray-500 ml-2 capitalize">{group.experience}</span>
          {!isCommander && <span className="text-gray-500 ml-1">× {group.count}</span>}
        </div>
        <span className="font-bold">{cost} pts</span>
      </div>

      {stats && (
        <div className="mt-1 text-xs text-gray-600 grid grid-cols-5 gap-2 w-64">
          <span>Mv {stats.move}&quot;</span>
          <span>Att {stats.attack}</span>
          <span>Def {stats.defence}</span>
          <span>Mor {stats.morale}</span>
          <span>Act {stats.actions}</span>
        </div>
      )}

      {equipParts.length > 0 && (
        <p className="mt-1 text-xs text-gray-500">{equipParts.join(', ')}</p>
      )}
      {cgUpgrades.length > 0 && (
        <p className="mt-0.5 text-xs text-gray-500">[{cgUpgrades.join(', ')}]</p>
      )}
      {abilities && (
        <p className="mt-0.5 text-xs text-gray-400 italic">{abilities}</p>
      )}
    </div>
  )
}
