'use client'

import { useRetinue } from '@/src/hooks/useRetinue'
import { computeGroupCost } from '@/src/logic/costs'
import { unitTypeById } from '@/src/data/unitTypes'
import { weaponById, armourById, shieldById, mountById } from '@/src/data/equipment'
import { abilityById } from '@/src/data/abilities'
import { dpAbilityById } from '@/src/data/dramatisPersonae'
import type { Group } from '@/src/types'

// This component is rendered off-screen and captured by html2canvas for Discord sharing.
// Styled for dark background with light text, A5-ish proportions.

export function RetinueSummaryCard() {
  const { retinue, totalCost } = useRetinue()

  return (
    <div
      id="retinue-summary-card"
      style={{
        position: 'fixed',
        left: '-9999px',
        top: 0,
        width: '480px',
        background: '#0f1117',
        color: '#e8e0d0',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: '12px',
        padding: '20px',
        borderRadius: '12px',
        border: '1px solid #2a2f3d',
      }}
    >
      {/* Header */}
      <div style={{ borderBottom: '1px solid #2a2f3d', paddingBottom: '12px', marginBottom: '14px' }}>
        <h1 style={{ fontSize: '18px', fontWeight: 700, color: '#c8a96e', margin: 0, lineHeight: 1.2 }}>
          {retinue.name}
        </h1>
        <p style={{ margin: '4px 0 0', color: '#6b7280', fontSize: '11px' }}>
          The Barons' War · Feudal European · {totalCost} / {retinue.pointsLimit} pts
        </p>
      </div>

      {/* Groups */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        {retinue.groups.map(group => (
          <SummaryGroupRow key={group.id} group={group} />
        ))}
      </div>

      {/* Footer */}
      <div style={{ borderTop: '1px solid #2a2f3d', marginTop: '14px', paddingTop: '8px', display: 'flex', justifyContent: 'space-between', color: '#4b5563', fontSize: '10px' }}>
        <span>Generated by Barons' War Retinue Builder</span>
        <span style={{ fontWeight: 600, color: '#c8a96e' }}>Total: {totalCost} pts</span>
      </div>
    </div>
  )
}

function SummaryGroupRow({ group }: { group: Group }) {
  const unitType = unitTypeById[group.unitTypeId]
  if (!unitType) return null

  const cost = computeGroupCost(group)
  const isCommander = unitType.isCommander
  const equipment = isCommander && group.commander ? group.commander.equipment : group.equipment

  const equipParts: string[] = []
  if (equipment.meleeWeapon) equipParts.push(weaponById[equipment.meleeWeapon]?.name ?? '')
  if (equipment.rangedWeapon) equipParts.push(weaponById[equipment.rangedWeapon]?.name ?? '')
  if (equipment.armour) equipParts.push(armourById[equipment.armour]?.name ?? '')
  if (equipment.shield) equipParts.push(shieldById[equipment.shield]?.name ?? '')
  if (equipment.mount) equipParts.push(mountById[equipment.mount]?.name ?? '')

  const cgUpgrades: string[] = []
  if (group.commandGroupUpgrade.banner) cgUpgrades.push('Banner')
  if (group.commandGroupUpgrade.pennant) cgUpgrades.push('Pennant')
  if (group.commandGroupUpgrade.musician) cgUpgrades.push('Musician')
  if (group.commandGroupUpgrade.priest) cgUpgrades.push('Priest')

  const abilities = [
    ...(isCommander ? [] : unitType.inherentAbilities),
    ...(isCommander ? (group.commander?.purchasedAbilities ?? []) : group.purchasedAbilities),
  ].map(id => abilityById[id]?.name ?? dpAbilityById[id]?.name ?? id.replace(/_/g, ' ')).join(', ')

  const isRL = group.commander?.isRetinueLeader ?? false

  return (
    <div style={{ background: '#181d2a', borderRadius: '8px', padding: '10px 12px', borderLeft: '3px solid #c8a96e' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <span style={{ fontWeight: 600, fontSize: '13px' }}>
            {isRL && '★ '}
            {isCommander && group.commander?.name ? `${group.commander.name} · ` : ''}
            {unitType.name}
          </span>
          <span style={{ color: '#6b7280', marginLeft: '6px', fontSize: '11px', textTransform: 'capitalize' }}>
            {group.experience}
          </span>
          {!isCommander && (
            <span style={{ color: '#6b7280', marginLeft: '4px', fontSize: '11px' }}>
              × {group.count}
            </span>
          )}
        </div>
        <span style={{ fontWeight: 700, color: '#c8a96e', fontSize: '14px' }}>{cost} pts</span>
      </div>

      {equipParts.length > 0 && (
        <p style={{ margin: '4px 0 0', color: '#9ca3af', fontSize: '11px' }}>
          {equipParts.join(' · ')}
        </p>
      )}

      {cgUpgrades.length > 0 && (
        <p style={{ margin: '2px 0 0', color: '#9ca3af', fontSize: '11px' }}>
          [{cgUpgrades.join(', ')}]
        </p>
      )}

      {abilities && (
        <p style={{ margin: '2px 0 0', color: '#6b7280', fontSize: '10px', fontStyle: 'italic' }}>
          {abilities}
        </p>
      )}
    </div>
  )
}
